export enum TaskType {
  SPORT = "SPORT",
  SANTE = "SANTE",
  TRAVAIL = "TRAVAIL",
  LOISIRS = "LOISIRS",
}

export enum Status {
  FUTURE_UNSCHEDULED = "FUTURE_UNSCHEDULED",
  PAST_UNSCHEDULED = "PAST_UNSCHEDULED",
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  MISSED = "MISSED",
}

export enum ChallengeType {
  MONTHLY_TASK_GOAL = "MONTHLY_TASK_GOAL",
  STREAK_GOAL = "STREAK_GOAL",
  PERFECT_MONTH = "PERFECT_MONTH",
  TASK_TYPE_GOAL = "TASK_TYPE_GOAL",
}

export enum ChallengeStatus {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}
